services:
  find-a-friend-pg:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DATABASE=find-a-friend-db
    ports:
      - 5432:5432
